config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  root to: 'reservations#index'
  resources :reservations, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :api, path: '/api', as: :api, defaults: { format: 'json' } do
    scope module: :v1,as: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      root to: 'base#test', as: :root

      # Just to test authentication
      get 'test', to: 'base#test'
      resources :reservations, only: :create
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  has_many :reservations
  has_many :phone_numbers
  validates :email, :first_name, :last_name, presence: true
  validates_format_of :email, with: VALID_EMAIL_REGEX, allow_blank: true
  validates_uniqueness_of :email, case_sensitive: false, allow_blank: true

  def full_name
    [first_name, last_name].compact.join(' ')
  end
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :guest
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :start_date, :end_date, :nights, :adults, :currency, :payout_price, :security_price, :total_price, presence: :true
  belongs_to :guest
  before_save :set_description

  private
  def set_description
    return if self.description.present?
    return if guests.blank?
    self.description = [self.guests, (self.guests > 1 ? 'guests' : 'guest')].join(' ')
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  before_action :authenticate
 
  # include Response
  # include ExceptionHandler
 
  API_TOKEN = "sample-token"

  before_action :authenticate

  def test
    render json: { message: 'It works!' }, status: 200
  end

  private

  def authenticate
    authenticate_or_request_with_http_token do |token, options|
      ActiveSupport::SecurityUtils.secure_compare(token, API_TOKEN)
    end
  end
end

app/controllers/api/v1/reservations_controller.rb
module Api::V1
  class ReservationsController < BaseController
    def create
      res = ProcessReservation.new(reservation_params).call
      # I opted not to use activemodel serializers here to save time
      render json: { reservation: res.as_json(include: [:guest]) }
    rescue StandardError => e
      Rails.logger.error e.message
      render json: { error: { message: 'Unable to save reservation.', description: e.message } }, status: 402
    end

    private
    def reservation_params
      params.fetch(:reservation, {}).has_key?(:guest_details) ? permit_reservation_params_one : permit_reservation_params_two 
    end

    def permit_reservation_params_one
      params.require(:reservation).permit(
        :start_date,
        :end_date,
        :expected_payout_amount,
        :guest_email,
        :guest_first_name,
        :guest_last_name,
        :listing_security_price_accurate,
        :host_currency,
        :nights,
        :number_of_guests,
        :status_type,
        :total_paid_amount_accurate,
        guest_phone_numbers: [],
        guest_details: [
          :localized_description,
          :number_of_adults,
          :number_of_children,
          :number_of_infants,
        ]
      )
    end

    def permit_reservation_params_two
      params.permit(
        :start_date,
        :end_date,
        :nights,
        :guests,  
        :adults,
        :children,
        :infants,
        :status,
        :currency,
        :payout_price,
        :security_price,
        :total_price,
        guest: [
          :first_name,
          :last_name,
          :phone,
          :email,
        ]
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.includes(:guest).all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/1/edit
  def edit
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(
        :start_date,
        :end_date,
        :nights,
        :guests,  
        :adults,
        :children,
        :infants,
        :status,
        :currency,
        :payout_price,
        :security_price,
        :total_price,
        :description
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HometimeReservations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reser: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Nights</th>
      <th>No. of guests</th>
      <th>Guest Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |res| %>
      <tr>
        <td><%= link_to res.id, reservation_path(res) %>
        <td><%= link_to res.nights %>
        <td><%= link_to res.guests %>
        <td><%= res.guest.full_name %>
        <td><%= link_to 'Show', res %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<table>
<tbody>
  <tr>
    <td>ID</td>
    <td><%= @reservation.id%></td>
  </tr>
  <tr>
    <td>Start Date</td>
    <td><%= @reservation.start_date%></td>
  </tr>
  <tr>
    <td>End Date</td>
    <td><%= @reservation.end_date%></td>
  </tr>
  <tr>
    <td>Nights</td>
    <td><%= @reservation.nights%></td>
  </tr>
  <tr>
    <td>Guests</td>
    <td><%= @reservation.guests %></td>
  </tr>
  <tr>
    <td>Adult</td>
    <td><%= @reservation.adults %></td>
  </tr>
  <tr>
    <td>Children</td>
    <td><%= @reservation.children %></td>
  </tr>
  <tr>
    <td>Infants</td>
    <td><%= @reservation.infants %></td>
  </tr>
  <tr>
    <td>Guest Email</td>
    <td><%= @reservation.guest.email %></td>
  </tr>
  <tr>
    <td>Guest Name</td>
    <td><%= @reservation.guest.full_name %></td>
  </tr>
  <tr>
    <td>Guest Phone Numbers</td>
    <td><%= @reservation.guest.phone_numbers.pluck(:number).join('<br/>').html_safe %></td>
  </tr>
  <tr>
    <td>Currency</td>
    <td><%= @reservation.currency %></td>
  </tr>
  <tr>
    <td>Payout Amount</td>
    <td><%= number_to_currency @reservation.payout_price, precision: 2 %></td>
  </tr>
  <tr>
    <td>Security Price</td>
    <td><%= number_to_currency @reservation.security_price, precision: 2 %></td>
  </tr>
   <tr>
    <td>Total Price</td>
    <td><%= number_to_currency @reservation.total_price, precision: 2 %></td>
  </tr>
</tbody>
</table>
<br/>
<%= link_to 'Back', reservations_path %>